### ISSUE TITLE
碰到Empty IMU measurements vector!!! 错误

### ISSUE THREAD

**Issue by jieli1990** [lturing/ORB_SLAM3_FAST_IMU_INIT#2]
如题，使用d435i运行rgbd模式，输入数据时，是有imu数据的，但是会有某个时刻出现Empty IMU measurements vector!!! ，然后程序直接挂掉。目前在找原因，是否是时间戳的问题。

**Comment by lturing** [comment]
可能是数据问题，相邻图像帧间没有 imu数据
